Add UserGuide example of march=native build
MDAnalysis/UserGuide pull request #177
Opened 2021-10-20 11:37 UTC by hmacdope

Introduction of the possibility of using the "march=native" build option in setup.cfg properly (see https://github.com/MDAnalysis/mdanalysis/pull/3429) means that we need some documentation to match.

It is critical to explain why this option is advanced and potential pitfalls, hence the warning and example.

NB do not merge if/until PR in MDA core is merged.

2021-10-20 11:48 UTC, richardjgowers requested changes

2021-10-20 11:48 UTC, richardjgowers commented on doc/source/installation.rst
> +
Add in recommendation to run tests with the new build?

2021-12-07 02:45 UTC, hmacdope commented
@MDAnalysis/coredevs could I snag a review on this?

2021-12-07 07:07 UTC, lilyminium requested changes

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +.. code-block:: YAML
I don't think this is yaml? Does a diff work in sphinx?


```
.. code-block:: diff

	- #extra_cflags = 
	+ extra_cflags = -march=native -mtune=native
```

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +Be sure to use the recommended flags for your target architecture. For example, ARM platforms reccomend against the use of `-mtune` in favour of `-mcpu`, while
```suggestion
Be sure to use the recommended flags for your target architecture. For example, ARM platforms recommend using ``-mcpu`` *instead* of ``-mcpu``, while
```

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +PowerPC platforms prefer both `-mcpu` and `-mtune`.
```suggestion
PowerPC platforms prefer *both* ``-mcpu`` and ``-mtune``.
```

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +Full dicussion of the these flags is available elsewhere and a list of supported options should be provided by your compiler. The list for GCC_ is provided here.
> elsewhere

A link would be handy, or terms for googling.

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +    making it usable only on a matching CPU architecture to the one it is compiled on. We **strongly** recommend that you run the testsuite on your intended platform
```suggestion
    making it usable only on a matching CPU architecture to the one it is compiled on. We **strongly** recommend that you run the test suite on your intended platform
```

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +    before proceeding.
```suggestion
    before proceeding with analysis.
```

Otherwise it sounds like we're to run the test suite before proceeding with compilation.

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +compute node you run MDAnalysis on have different CPU architectures, you should avoid this option unless you know what you are doing, or you should compile directly on the compute node.
```suggestion
In cases where you might encounter multiple CPU architectures (e.g. on a supercomputer where the login node and compute node have different architectures), you should avoid changing these options unless you are experienced with compiling software in these situations.
```

This is really long. It also implies that it's common to compile on the login node, whereas I feel like hpc people are really really *against* that kind of shenanigan.

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +You can pass any additional compiler flags for the C/C++ compiler using the `extra_cflags` variable in `setup.cfg`.
```suggestion
You can pass any additional compiler flags for the C/C++ compiler using the ``extra_cflags`` variable in ``setup.cfg``.
```

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +This option can also be used to tune your MDAnalysis installation for your current architecture using `-march`, `-mtune`, `-mcpu` and related compiler flags.
```suggestion
For example, ``extra_cflags`` can also be used to tune your MDAnalysis installation for your current architecture using the `-march`, `-mtune`, `-mcpu` and related compiler flags.
```

Which option?

2021-12-07 07:07 UTC, lilyminium commented on doc/source/installation.rst
> +The use of these compiler flags allows CPU architecture specific optimisations. An example for an x86_64 machine would be to change the
```suggestion
*Which* particular compiler flags to use depends on your CPU architecture. An example for an x86_64 machine would be to change the
```

2021-12-07 07:15 UTC, hmacdope commented
Legendary @lilyminium thanks so much. It seems I can't spell.

2021-12-07 10:25 UTC, hmacdope commented
All fixed up I think.

2021-12-07 14:41 UTC, lilyminium commented on doc/source/installation.rst
> +For example, ``extra_cflags`` can also be used to tune your MDAnalysis installation for your current architecture using the `-march`, `-mtune`, `-mcpu` and related compiler flags.
```suggestion
For example, ``extra_cflags`` can be used to tune your MDAnalysis installation for your current architecture using the `-march`, `-mtune`, `-mcpu` and related compiler flags.
```

2021-12-07 14:42 UTC, lilyminium approved these changes
Oops, caught another little thing. Otherwise all good to go, but could you please add yourself to AUTHORS?

2021-12-08 00:20 UTC, merged