Fix nbval testing failures due to new 0.10 release
MDAnalysis/UserGuide pull request #251
Opened 2023-01-13 09:02 UTC by pgbarletta

From #248 and #249

- I filed an issue on nbval(https://github.com/computationalmodelling/nbval/issues/194) where I explain what changed.
For now, I removed all semicolons that were used to silence cell outputs and added the necessary additional sanitize statements on `tests/sanitize_output.cfg`
- Also unpinned nbval

One small drawback is that for now I can't silence this ugly plots:
![ugly_plot](https://user-images.githubusercontent.com/5693483/212280156-7ac360f1-414c-429d-8ec0-333d7aa9b95b.png)

2023-06-09 10:05 UTC, pgbarletta commented
Should I close this?

2023-06-09 10:12 UTC, IAlibay commented
> Should I close this?

I have no context for this fix, is it still a necessary change in your opinion?

2023-06-09 10:26 UTC, pgbarletta commented
Well, this was done to fix #248 and #249, and back then it worked (IDK why it's failing right now).
But then it seems that you pinned nbval on #250 and carried on.
I could rebase this branch, make everything pass again and unpin nbval if you want.

The nbval bug that caused this is still there by the way.

2023-06-09 11:13 UTC, IAlibay commented
> Well, this was done to fix #248 and #249, and back then it worked (IDK why it's failing right now). But then it seems that you pinned nbval on #250 and carried on. I could rebase this branch, make everything pass again and unpin nbval if you want.
> 
> The nbval bug that caused this is still there by the way.

Ok, yeah it looks like this fix is still necessary. If you have the capacity to work out why things are failing now then that'd be great. Please go ahead and ping the whole coredevs group when you need a review (I don't spend a lot of time looking at this repo unfortunately).

(#250 was just a temporary fix so I could get a release out)

2023-06-09 17:39 UTC, pgbarletta commented
@MDAnalysis/coredevs Done!

No big changes here. Just sanitizing notebooks* so nbval tests pass without the need of pinning it to an older version.

*: that is, adding regex expressions so outputs that necessarily vary from execution to execution (eg: data structures' memory locations) don't make nbval fail spuriously.

2023-06-09 18:52 UTC, IAlibay commented on doc/source/examples/analysis/alignment_and_rms/aligning_trajectory_to_frame.ipynb
Why such a large delta here?

2023-06-09 19:10 UTC, pgbarletta commented on doc/source/examples/analysis/alignment_and_rms/aligning_trajectory_to_frame.ipynb
again, accumulated widgets. That one was the heaviest.

2023-06-10 05:41 UTC, lilyminium requested changes
Thanks @pgbarletta for getting on this. Looks good, just a suggestion: `ax = ps.plot(...)` should still show the plot, I think, but with a much smaller output.
<img width="557" alt="Screenshot 2023-06-10 at 3 41 35 pm" src="https://github.com/MDAnalysis/UserGuide/assets/31115101/2b950966-4e46-4077-843f-5840f5a87c5a">

2023-06-10 07:36 UTC, lilyminium approved these changes
LGTM!

Sorry for all the conflicts...

2023-06-10 10:35 UTC, pgbarletta commented
> LGTM!
> 
> Sorry for all the conflicts...

Yeah, do you know why they showed up all of a sudden?

2023-06-10 13:41 UTC, lilyminium commented
I'm guessing because I merged #256 -- the widget states might be conflicting?

2023-06-10 14:24 UTC, pgbarletta commented
ah, right, it's gotta be that.

2023-06-12 11:10 UTC, IAlibay commented
Just saw the review request - apologies @pgbarletta I'm kinda checked out of userguide things for the time being. I'm leaving it up to @lilyminium to take this towards a merge.

2023-06-13 01:10 UTC, lilyminium commented
@pgbarletta are you up for fixing the merge conflicts? Otherwise this PR is good to go :)

2023-06-14 08:27 UTC, pgbarletta commented
Done! Removed all the widget attributes.

2023-06-14 21:49 UTC, lilyminium commented
Thanks so much for this @pgbarletta!

2023-06-14 21:49 UTC, merged