dev: add isort to pre commit
MDAnalysis/UserGuide pull request #284
Opened 2023-07-30 20:15 UTC by jandom

follow-up to https://github.com/MDAnalysis/UserGuide/pull/283 which adds isort to pre-commit

2023-08-04 10:53 UTC, jandom commented
@RMeli sorry to ping you again, maybe you could give this a quick review? (isort added to pre-commit config)

2023-08-06 01:44 UTC, lilyminium approved these changes
LGTM -- thanks for adding this @jandom :)

2023-08-06 08:39 UTC, RMeli requested changes
Thanks @jandom! I merged #283, so if you merge/rebase and then add 5ff083b144c37beb64b27600add967c8a73766ce to `.git-blame-ignore-revs` we are good to go.

Sorry for the slow replies/reviews these days.

2023-08-06 11:30 UTC, jandom commented
@RMeli awesome work, many thanks – getting all our ducks in a row :-)

2023-08-06 11:41 UTC, merged