updated line length in code contrib section
MDAnalysis/UserGuide pull request #348
Opened 2023-12-01 18:37 UTC by orbeckst

- fix #347
- add note on black

----
:books: Documentation preview :books:: https://mdanalysisuserguide--348.org.readthedocs.build/en/348/

2023-12-10 06:59 UTC, lilyminium requested changes
Thanks for the change, @orbeckst! Just one minor change.

2023-12-10 06:59 UTC, lilyminium commented on doc/source/contributing_code.rst
> +   * Do **not run ``black`` on an existing file** that you are editing. This makes the diff for the PR very difficult to read. Instead use ``darker`` as explained above to only reformat your changes.
Some interaction with bolding makes the backticks not render properly, unfortunately.

```suggestion
   * **Do not run** ``black`` on an existing file that you are editing. This makes the diff for the PR very difficult to read. Instead use ``darker`` as explained above to only reformat your changes.
```

2024-01-13 00:05 UTC, orbeckst commented
Sorry @lilyminium this one totally slipped off my radar. Thank you for the suggested fix.

2024-01-15 11:42 UTC, lilyminium approved these changes
LGTM, thank you for picking this up again @orbeckst!

2024-01-15 11:42 UTC, merged