Update link for GSoD 2019
MDAnalysis/UserGuide pull request #381
Opened 2024-09-14 13:28 UTC by mhmohona

Updated link for GSoD 2019 in `Readme.rst`.

2024-09-14 15:03 UTC, lilyminium requested changes
LGTM -- thanks @mhmohona! Could you please add yourself to [AUTHORS](https://github.com/MDAnalysis/UserGuide/blob/develop/doc/source/AUTHORS)?

2024-09-14 20:00 UTC, RMeli approved these changes

2024-09-15 00:25 UTC, lilyminium approved these changes

2024-09-15 01:36 UTC, lilyminium commented
Thanks for the fix @mhmohona!

2024-09-15 01:36 UTC, merged