Fix duplicate level for `trajectory-similarity` level
MDAnalysis/UserGuide pull request #386
Opened 2024-09-26 04:55 UTC by mhmohona

Fix duplicate level for `trajectory-similarity` level by updating the tag. 

Closes #375

2024-09-26 20:11 UTC, RMeli commented
Hi @mhmohona, I don't think this solves the issue, does it? CI still shows the error, with the new tag:

```
/home/runner/work/UserGuide/UserGuide/doc/source/examples/analysis/trajectory_similarity/README.rst:6: WARNING: duplicate label trajectory-similarity-analysis, other instance in /home/runner/work/UserGuide/UserGuide/doc/source/examples/analysis/README.rst
```

https://github.com/MDAnalysis/UserGuide/actions/runs/11045817485/job/30684095342?pr=386#step:7:273

2024-12-18 05:06 UTC, orbeckst commented
@mhmohona do you have the time to come back to this PR or should we close it?

2024-12-18 06:30 UTC, mhmohona commented
@orbeckst,I will work on it. However I had some confusion here, thus marked it as draft.

2025-03-24 19:47 UTC, orbeckst requested changes
fixing the ref

2025-03-24 19:47 UTC, orbeckst commented on doc/source/examples/analysis/reduced_dimensions/README.rst
> +For computing similarity, see the tutorials in :ref:`_trajectory-similarity-overview`.
```suggestion
For computing similarity, see the tutorials in :ref:`trajectory-similarity-overview`.
```

2025-03-24 19:54 UTC, orbeckst commented
The build still shows the warning
```
/home/runner/work/UserGuide/UserGuide/doc/source/examples/analysis/trajectory_similarity/README.rst:6: WARNING: duplicate label trajectory-similarity-overview, other instance in /home/runner/work/UserGuide/UserGuide/doc/source/examples/analysis/README.rst
```

2026-02-16 04:48 UTC, closed without merging